[workspace]
resolver = "2"
members = [
    "actix-app",
    "amis-app",
    "axum-app",
    "dioxus-desktop",
    "dioxus-ssr",
    "minimal-app",
    "ntex-app",
]

[profile.release]
lto = "thin"
codegen-units = 1
strip = true
