[package]
name = "axum-app"
description = "An example for axum integration."
version = "0.14.2"
rust-version = "1.75"
edition = "2021"
publish = false

[dependencies]
tracing = "0.1.40"

[dependencies.axum]
version = "0.7.5"
default-features = false

[dependencies.serde]
version = "1.0.209"
features = ["derive"]

[dependencies.zino]
path = "../../zino"
version = "0.24.2"
features = [
    "axum",
    "i18n",
    "jwt",
    "orm",
]

[dependencies.zino-core]
path = "../../zino-core"
version = "0.25.2"
features = [
    "cookie",
    "env-filter",
    "orm-mysql",
    "validator-email",
    "view-tera",
]

[dependencies.zino-derive]
path = "../../zino-derive"
version = "0.22.2"

[dependencies.zino-model]
path = "../../zino-model"
version = "0.22.2"
