[package]
name = "minimal-app"
description = "A minimal example to run a server."
version = "0.4.0"
rust-version = "1.80"
edition = "2021"
publish = false

[dependencies.zino]
path = "../../zino"
version = "0.25.1"
features = ["axum"]

